# Generated by Django 3.0.2 on 2020-01-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('stock', models.CharField(max_length=10)),
            ],
        ),
    ]
