# Generated by Django 3.0.2 on 2020-01-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200127_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='total_price',
        ),
    ]
