# Generated by Django 3.0.2 on 2020-01-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200127_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product_id',
            new_name='product',
        ),
    ]
