# Generated by Django 3.0.2 on 2020-01-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200127_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
